### ISSUE TITLE
BS440csv: no new graphs

### ISSUE THREAD

**Issue by keptenkurk** [keptenkurk/BS440#46]
@DjZU Although data is updated, csv created, user-plot-31.html is updated i keep getting an old test picture i generated before clearing the csv to populate it with real scale data. 
Like render_template does not run...
Can't figure out where to look, any clue?

**Comment by DjZU** [comment]
@keptenkurk I switched debug=True to False before uploading the files here and this is the regression. I don't understand why but anyway I switched debug back to True and remove the logging part for BS4440flask.py since it is not useful in production and would get very big with debug=True. I'll make a pull request.

**Comment by keptenkurk** [comment]
Thanks a lot! Updates fine now!
